services:
   webapi:
      build: .
      ports: 
         - "80:80"
      depends_on: 
         - database 
   database:
      image: postgres:13.1
      volumes:
         - postgres/data:/var/lib/postgres/data
      environment:
         POSTGRES_PASSWORD: minhasupersenha
      ports:
         - "5432:5432"