services:
   webapi:
      build:
         context: .
         dockerfile: Dockerfile
      ports: 
         - "80:80"
      depends_on: 
         - database 
   database:
      image: postgres:13.1
      volumes:
         - /var/lib/postgres/data
      environment:
         POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      ports:
         - "5432:5432"